# coding: utf-8

"""
    Federated Content API

    Welcome to the Federated Content API following Open API Specification (Version 3.0.0)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.integrations_id_body import IntegrationsIdBody  # noqa: E501
from swagger_client.rest import ApiException


class TestIntegrationsIdBody(unittest.TestCase):
    """IntegrationsIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrationsIdBody(self):
        """Test IntegrationsIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.integrations_id_body.IntegrationsIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
