# coding: utf-8

"""
    Federated Content API

    Welcome to the Federated Content API following Open API Specification (Version 3.0.0)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.hotel_get_offer_availability_response import HotelGetOfferAvailabilityResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestHotelGetOfferAvailabilityResponse(unittest.TestCase):
    """HotelGetOfferAvailabilityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHotelGetOfferAvailabilityResponse(self):
        """Test HotelGetOfferAvailabilityResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.hotel_get_offer_availability_response.HotelGetOfferAvailabilityResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
