<?php
/**
 * ToursAndActivitiesOfferDetailsSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Federated Content API
 *
 * Welcome to the Federated Content API following Open API Specification (Version 3.0.0)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ToursAndActivitiesOfferDetailsSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description ToursAndActivitiesOfferDetailsSchema
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ToursAndActivitiesOfferDetailsSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ToursAndActivitiesOfferDetailsSchema"
     */
    public function testToursAndActivitiesOfferDetailsSchema()
    {
    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {
    }

    /**
     * Test attribute "supplier_offer_id"
     */
    public function testPropertySupplierOfferId()
    {
    }

    /**
     * Test attribute "offer_index"
     */
    public function testPropertyOfferIndex()
    {
    }

    /**
     * Test attribute "offer_tax"
     */
    public function testPropertyOfferTax()
    {
    }

    /**
     * Test attribute "offer_price"
     */
    public function testPropertyOfferPrice()
    {
    }

    /**
     * Test attribute "offer_currency"
     */
    public function testPropertyOfferCurrency()
    {
    }

    /**
     * Test attribute "offer_cancelation_policies"
     */
    public function testPropertyOfferCancelationPolicies()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "adults"
     */
    public function testPropertyAdults()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }

    /**
     * Test attribute "tour_name"
     */
    public function testPropertyTourName()
    {
    }

    /**
     * Test attribute "tour_description"
     */
    public function testPropertyTourDescription()
    {
    }

    /**
     * Test attribute "tour_address"
     */
    public function testPropertyTourAddress()
    {
    }

    /**
     * Test attribute "tour_latitude"
     */
    public function testPropertyTourLatitude()
    {
    }

    /**
     * Test attribute "tour_longitude"
     */
    public function testPropertyTourLongitude()
    {
    }

    /**
     * Test attribute "tour_distance"
     */
    public function testPropertyTourDistance()
    {
    }

    /**
     * Test attribute "tour_distance_metric"
     */
    public function testPropertyTourDistanceMetric()
    {
    }

    /**
     * Test attribute "tour_images"
     */
    public function testPropertyTourImages()
    {
    }

    /**
     * Test attribute "tour_rating"
     */
    public function testPropertyTourRating()
    {
    }

    /**
     * Test attribute "tour_reviews"
     */
    public function testPropertyTourReviews()
    {
    }

    /**
     * Test attribute "tour_subcategories"
     */
    public function testPropertyTourSubcategories()
    {
    }

    /**
     * Test attribute "booking_questions"
     */
    public function testPropertyBookingQuestions()
    {
    }

    /**
     * Test attribute "variants"
     */
    public function testPropertyVariants()
    {
    }
}
