/*
 * Federated Content API
 * Welcome to the Federated Content API following Open API Specification (Version 3.0.0)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.HotelRoomSchema;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.threeten.bp.LocalDate;
/**
 * HotelOfferDetailsSchema
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-24T14:14:21.689997473Z[GMT]")

public class HotelOfferDetailsSchema {
  @SerializedName("offer_id")
  private UUID offerId = null;

  @SerializedName("supplier_offer_id")
  private UUID supplierOfferId = null;

  @SerializedName("offer_index")
  private Integer offerIndex = null;

  @SerializedName("offer_tax")
  private Double offerTax = null;

  @SerializedName("offer_price")
  private Double offerPrice = null;

  @SerializedName("offer_currency")
  private String offerCurrency = null;

  @SerializedName("offer_cancellation_policies")
  private Object offerCancellationPolicies = null;

  @SerializedName("checkin_date")
  private LocalDate checkinDate = null;

  @SerializedName("checkout_date")
  private LocalDate checkoutDate = null;

  @SerializedName("hotel_name")
  private String hotelName = null;

  @SerializedName("hotel_description")
  private String hotelDescription = null;

  @SerializedName("hotel_address")
  private String hotelAddress = null;

  @SerializedName("hotel_latitude")
  private Float hotelLatitude = null;

  @SerializedName("hotel_longitude")
  private Float hotelLongitude = null;

  @SerializedName("hotel_distance")
  private Double hotelDistance = null;

  @SerializedName("hotel_distance_metric")
  private String hotelDistanceMetric = null;

  @SerializedName("hotel_images")
  private List<String> hotelImages = null;

  @SerializedName("hotel_rating")
  private Float hotelRating = null;

  @SerializedName("hotel_reviews")
  private Object hotelReviews = null;

  @SerializedName("hotel_stars")
  private Integer hotelStars = null;

  @SerializedName("hotel_checkin_time")
  private String hotelCheckinTime = null;

  @SerializedName("hotel_checkout_time")
  private String hotelCheckoutTime = null;

  @SerializedName("hotel_facilities")
  private List<String> hotelFacilities = null;

  @SerializedName("hotel_amenities")
  private List<String> hotelAmenities = null;

  @SerializedName("hotel_policies")
  private List<String> hotelPolicies = null;

  @SerializedName("rooms")
  private List<HotelRoomSchema> rooms = null;

  public HotelOfferDetailsSchema offerId(UUID offerId) {
    this.offerId = offerId;
    return this;
  }

   /**
   * Unique identifier for the hotel offer.
   * @return offerId
  **/
  @Schema(description = "Unique identifier for the hotel offer.")
  public UUID getOfferId() {
    return offerId;
  }

  public void setOfferId(UUID offerId) {
    this.offerId = offerId;
  }

  public HotelOfferDetailsSchema supplierOfferId(UUID supplierOfferId) {
    this.supplierOfferId = supplierOfferId;
    return this;
  }

   /**
   * Unique identifier given by the supplier for the hotel offer.
   * @return supplierOfferId
  **/
  @Schema(description = "Unique identifier given by the supplier for the hotel offer.")
  public UUID getSupplierOfferId() {
    return supplierOfferId;
  }

  public void setSupplierOfferId(UUID supplierOfferId) {
    this.supplierOfferId = supplierOfferId;
  }

  public HotelOfferDetailsSchema offerIndex(Integer offerIndex) {
    this.offerIndex = offerIndex;
    return this;
  }

   /**
   * Index number of the offer for sorting and referencing purposes.
   * @return offerIndex
  **/
  @Schema(description = "Index number of the offer for sorting and referencing purposes.")
  public Integer getOfferIndex() {
    return offerIndex;
  }

  public void setOfferIndex(Integer offerIndex) {
    this.offerIndex = offerIndex;
  }

  public HotelOfferDetailsSchema offerTax(Double offerTax) {
    this.offerTax = offerTax;
    return this;
  }

   /**
   * Applicable tax amount for the offer.
   * @return offerTax
  **/
  @Schema(description = "Applicable tax amount for the offer.")
  public Double getOfferTax() {
    return offerTax;
  }

  public void setOfferTax(Double offerTax) {
    this.offerTax = offerTax;
  }

  public HotelOfferDetailsSchema offerPrice(Double offerPrice) {
    this.offerPrice = offerPrice;
    return this;
  }

   /**
   * Total price of the hotel offer.
   * @return offerPrice
  **/
  @Schema(description = "Total price of the hotel offer.")
  public Double getOfferPrice() {
    return offerPrice;
  }

  public void setOfferPrice(Double offerPrice) {
    this.offerPrice = offerPrice;
  }

  public HotelOfferDetailsSchema offerCurrency(String offerCurrency) {
    this.offerCurrency = offerCurrency;
    return this;
  }

   /**
   * Currency in which the offer price is denominated.
   * @return offerCurrency
  **/
  @Schema(description = "Currency in which the offer price is denominated.")
  public String getOfferCurrency() {
    return offerCurrency;
  }

  public void setOfferCurrency(String offerCurrency) {
    this.offerCurrency = offerCurrency;
  }

  public HotelOfferDetailsSchema offerCancellationPolicies(Object offerCancellationPolicies) {
    this.offerCancellationPolicies = offerCancellationPolicies;
    return this;
  }

   /**
   * Details of the cancellation policies applicable to the offer.
   * @return offerCancellationPolicies
  **/
  @Schema(description = "Details of the cancellation policies applicable to the offer.")
  public Object getOfferCancellationPolicies() {
    return offerCancellationPolicies;
  }

  public void setOfferCancellationPolicies(Object offerCancellationPolicies) {
    this.offerCancellationPolicies = offerCancellationPolicies;
  }

  public HotelOfferDetailsSchema checkinDate(LocalDate checkinDate) {
    this.checkinDate = checkinDate;
    return this;
  }

   /**
   * Scheduled check-in date for the hotel stay.
   * @return checkinDate
  **/
  @Schema(description = "Scheduled check-in date for the hotel stay.")
  public LocalDate getCheckinDate() {
    return checkinDate;
  }

  public void setCheckinDate(LocalDate checkinDate) {
    this.checkinDate = checkinDate;
  }

  public HotelOfferDetailsSchema checkoutDate(LocalDate checkoutDate) {
    this.checkoutDate = checkoutDate;
    return this;
  }

   /**
   * Scheduled check-out date for the hotel stay.
   * @return checkoutDate
  **/
  @Schema(description = "Scheduled check-out date for the hotel stay.")
  public LocalDate getCheckoutDate() {
    return checkoutDate;
  }

  public void setCheckoutDate(LocalDate checkoutDate) {
    this.checkoutDate = checkoutDate;
  }

  public HotelOfferDetailsSchema hotelName(String hotelName) {
    this.hotelName = hotelName;
    return this;
  }

   /**
   * Name of the hotel.
   * @return hotelName
  **/
  @Schema(description = "Name of the hotel.")
  public String getHotelName() {
    return hotelName;
  }

  public void setHotelName(String hotelName) {
    this.hotelName = hotelName;
  }

  public HotelOfferDetailsSchema hotelDescription(String hotelDescription) {
    this.hotelDescription = hotelDescription;
    return this;
  }

   /**
   * Description of the hotel.
   * @return hotelDescription
  **/
  @Schema(description = "Description of the hotel.")
  public String getHotelDescription() {
    return hotelDescription;
  }

  public void setHotelDescription(String hotelDescription) {
    this.hotelDescription = hotelDescription;
  }

  public HotelOfferDetailsSchema hotelAddress(String hotelAddress) {
    this.hotelAddress = hotelAddress;
    return this;
  }

   /**
   * Physical address of the hotel.
   * @return hotelAddress
  **/
  @Schema(description = "Physical address of the hotel.")
  public String getHotelAddress() {
    return hotelAddress;
  }

  public void setHotelAddress(String hotelAddress) {
    this.hotelAddress = hotelAddress;
  }

  public HotelOfferDetailsSchema hotelLatitude(Float hotelLatitude) {
    this.hotelLatitude = hotelLatitude;
    return this;
  }

   /**
   * Geographic latitude of the hotel.
   * @return hotelLatitude
  **/
  @Schema(description = "Geographic latitude of the hotel.")
  public Float getHotelLatitude() {
    return hotelLatitude;
  }

  public void setHotelLatitude(Float hotelLatitude) {
    this.hotelLatitude = hotelLatitude;
  }

  public HotelOfferDetailsSchema hotelLongitude(Float hotelLongitude) {
    this.hotelLongitude = hotelLongitude;
    return this;
  }

   /**
   * Geographic longitude of the hotel.
   * @return hotelLongitude
  **/
  @Schema(description = "Geographic longitude of the hotel.")
  public Float getHotelLongitude() {
    return hotelLongitude;
  }

  public void setHotelLongitude(Float hotelLongitude) {
    this.hotelLongitude = hotelLongitude;
  }

  public HotelOfferDetailsSchema hotelDistance(Double hotelDistance) {
    this.hotelDistance = hotelDistance;
    return this;
  }

   /**
   * Distance of the hotel from a central point of interest, if applicable.
   * @return hotelDistance
  **/
  @Schema(description = "Distance of the hotel from a central point of interest, if applicable.")
  public Double getHotelDistance() {
    return hotelDistance;
  }

  public void setHotelDistance(Double hotelDistance) {
    this.hotelDistance = hotelDistance;
  }

  public HotelOfferDetailsSchema hotelDistanceMetric(String hotelDistanceMetric) {
    this.hotelDistanceMetric = hotelDistanceMetric;
    return this;
  }

   /**
   * Unit of measurement for the distance (e.g., km, miles).
   * @return hotelDistanceMetric
  **/
  @Schema(description = "Unit of measurement for the distance (e.g., km, miles).")
  public String getHotelDistanceMetric() {
    return hotelDistanceMetric;
  }

  public void setHotelDistanceMetric(String hotelDistanceMetric) {
    this.hotelDistanceMetric = hotelDistanceMetric;
  }

  public HotelOfferDetailsSchema hotelImages(List<String> hotelImages) {
    this.hotelImages = hotelImages;
    return this;
  }

  public HotelOfferDetailsSchema addHotelImagesItem(String hotelImagesItem) {
    if (this.hotelImages == null) {
      this.hotelImages = new ArrayList<String>();
    }
    this.hotelImages.add(hotelImagesItem);
    return this;
  }

   /**
   * Array of images associated with the hotel.
   * @return hotelImages
  **/
  @Schema(description = "Array of images associated with the hotel.")
  public List<String> getHotelImages() {
    return hotelImages;
  }

  public void setHotelImages(List<String> hotelImages) {
    this.hotelImages = hotelImages;
  }

  public HotelOfferDetailsSchema hotelRating(Float hotelRating) {
    this.hotelRating = hotelRating;
    return this;
  }

   /**
   * Overall rating of the hotel.
   * @return hotelRating
  **/
  @Schema(description = "Overall rating of the hotel.")
  public Float getHotelRating() {
    return hotelRating;
  }

  public void setHotelRating(Float hotelRating) {
    this.hotelRating = hotelRating;
  }

  public HotelOfferDetailsSchema hotelReviews(Object hotelReviews) {
    this.hotelReviews = hotelReviews;
    return this;
  }

   /**
   * Collection of reviews for the hotel.
   * @return hotelReviews
  **/
  @Schema(description = "Collection of reviews for the hotel.")
  public Object getHotelReviews() {
    return hotelReviews;
  }

  public void setHotelReviews(Object hotelReviews) {
    this.hotelReviews = hotelReviews;
  }

  public HotelOfferDetailsSchema hotelStars(Integer hotelStars) {
    this.hotelStars = hotelStars;
    return this;
  }

   /**
   * Star rating of the hotel.
   * @return hotelStars
  **/
  @Schema(description = "Star rating of the hotel.")
  public Integer getHotelStars() {
    return hotelStars;
  }

  public void setHotelStars(Integer hotelStars) {
    this.hotelStars = hotelStars;
  }

  public HotelOfferDetailsSchema hotelCheckinTime(String hotelCheckinTime) {
    this.hotelCheckinTime = hotelCheckinTime;
    return this;
  }

   /**
   * Standard check-in time at the hotel.
   * @return hotelCheckinTime
  **/
  @Schema(description = "Standard check-in time at the hotel.")
  public String getHotelCheckinTime() {
    return hotelCheckinTime;
  }

  public void setHotelCheckinTime(String hotelCheckinTime) {
    this.hotelCheckinTime = hotelCheckinTime;
  }

  public HotelOfferDetailsSchema hotelCheckoutTime(String hotelCheckoutTime) {
    this.hotelCheckoutTime = hotelCheckoutTime;
    return this;
  }

   /**
   * Standard check-out time at the hotel.
   * @return hotelCheckoutTime
  **/
  @Schema(description = "Standard check-out time at the hotel.")
  public String getHotelCheckoutTime() {
    return hotelCheckoutTime;
  }

  public void setHotelCheckoutTime(String hotelCheckoutTime) {
    this.hotelCheckoutTime = hotelCheckoutTime;
  }

  public HotelOfferDetailsSchema hotelFacilities(List<String> hotelFacilities) {
    this.hotelFacilities = hotelFacilities;
    return this;
  }

  public HotelOfferDetailsSchema addHotelFacilitiesItem(String hotelFacilitiesItem) {
    if (this.hotelFacilities == null) {
      this.hotelFacilities = new ArrayList<String>();
    }
    this.hotelFacilities.add(hotelFacilitiesItem);
    return this;
  }

   /**
   * List of facilities available at the hotel.
   * @return hotelFacilities
  **/
  @Schema(description = "List of facilities available at the hotel.")
  public List<String> getHotelFacilities() {
    return hotelFacilities;
  }

  public void setHotelFacilities(List<String> hotelFacilities) {
    this.hotelFacilities = hotelFacilities;
  }

  public HotelOfferDetailsSchema hotelAmenities(List<String> hotelAmenities) {
    this.hotelAmenities = hotelAmenities;
    return this;
  }

  public HotelOfferDetailsSchema addHotelAmenitiesItem(String hotelAmenitiesItem) {
    if (this.hotelAmenities == null) {
      this.hotelAmenities = new ArrayList<String>();
    }
    this.hotelAmenities.add(hotelAmenitiesItem);
    return this;
  }

   /**
   * List of amenities offered by the hotel.
   * @return hotelAmenities
  **/
  @Schema(description = "List of amenities offered by the hotel.")
  public List<String> getHotelAmenities() {
    return hotelAmenities;
  }

  public void setHotelAmenities(List<String> hotelAmenities) {
    this.hotelAmenities = hotelAmenities;
  }

  public HotelOfferDetailsSchema hotelPolicies(List<String> hotelPolicies) {
    this.hotelPolicies = hotelPolicies;
    return this;
  }

  public HotelOfferDetailsSchema addHotelPoliciesItem(String hotelPoliciesItem) {
    if (this.hotelPolicies == null) {
      this.hotelPolicies = new ArrayList<String>();
    }
    this.hotelPolicies.add(hotelPoliciesItem);
    return this;
  }

   /**
   * General policies of the hotel.
   * @return hotelPolicies
  **/
  @Schema(description = "General policies of the hotel.")
  public List<String> getHotelPolicies() {
    return hotelPolicies;
  }

  public void setHotelPolicies(List<String> hotelPolicies) {
    this.hotelPolicies = hotelPolicies;
  }

  public HotelOfferDetailsSchema rooms(List<HotelRoomSchema> rooms) {
    this.rooms = rooms;
    return this;
  }

  public HotelOfferDetailsSchema addRoomsItem(HotelRoomSchema roomsItem) {
    if (this.rooms == null) {
      this.rooms = new ArrayList<HotelRoomSchema>();
    }
    this.rooms.add(roomsItem);
    return this;
  }

   /**
   * Array of HotelRoomSchema.
   * @return rooms
  **/
  @Schema(description = "Array of HotelRoomSchema.")
  public List<HotelRoomSchema> getRooms() {
    return rooms;
  }

  public void setRooms(List<HotelRoomSchema> rooms) {
    this.rooms = rooms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HotelOfferDetailsSchema hotelOfferDetailsSchema = (HotelOfferDetailsSchema) o;
    return Objects.equals(this.offerId, hotelOfferDetailsSchema.offerId) &&
        Objects.equals(this.supplierOfferId, hotelOfferDetailsSchema.supplierOfferId) &&
        Objects.equals(this.offerIndex, hotelOfferDetailsSchema.offerIndex) &&
        Objects.equals(this.offerTax, hotelOfferDetailsSchema.offerTax) &&
        Objects.equals(this.offerPrice, hotelOfferDetailsSchema.offerPrice) &&
        Objects.equals(this.offerCurrency, hotelOfferDetailsSchema.offerCurrency) &&
        Objects.equals(this.offerCancellationPolicies, hotelOfferDetailsSchema.offerCancellationPolicies) &&
        Objects.equals(this.checkinDate, hotelOfferDetailsSchema.checkinDate) &&
        Objects.equals(this.checkoutDate, hotelOfferDetailsSchema.checkoutDate) &&
        Objects.equals(this.hotelName, hotelOfferDetailsSchema.hotelName) &&
        Objects.equals(this.hotelDescription, hotelOfferDetailsSchema.hotelDescription) &&
        Objects.equals(this.hotelAddress, hotelOfferDetailsSchema.hotelAddress) &&
        Objects.equals(this.hotelLatitude, hotelOfferDetailsSchema.hotelLatitude) &&
        Objects.equals(this.hotelLongitude, hotelOfferDetailsSchema.hotelLongitude) &&
        Objects.equals(this.hotelDistance, hotelOfferDetailsSchema.hotelDistance) &&
        Objects.equals(this.hotelDistanceMetric, hotelOfferDetailsSchema.hotelDistanceMetric) &&
        Objects.equals(this.hotelImages, hotelOfferDetailsSchema.hotelImages) &&
        Objects.equals(this.hotelRating, hotelOfferDetailsSchema.hotelRating) &&
        Objects.equals(this.hotelReviews, hotelOfferDetailsSchema.hotelReviews) &&
        Objects.equals(this.hotelStars, hotelOfferDetailsSchema.hotelStars) &&
        Objects.equals(this.hotelCheckinTime, hotelOfferDetailsSchema.hotelCheckinTime) &&
        Objects.equals(this.hotelCheckoutTime, hotelOfferDetailsSchema.hotelCheckoutTime) &&
        Objects.equals(this.hotelFacilities, hotelOfferDetailsSchema.hotelFacilities) &&
        Objects.equals(this.hotelAmenities, hotelOfferDetailsSchema.hotelAmenities) &&
        Objects.equals(this.hotelPolicies, hotelOfferDetailsSchema.hotelPolicies) &&
        Objects.equals(this.rooms, hotelOfferDetailsSchema.rooms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerId, supplierOfferId, offerIndex, offerTax, offerPrice, offerCurrency, offerCancellationPolicies, checkinDate, checkoutDate, hotelName, hotelDescription, hotelAddress, hotelLatitude, hotelLongitude, hotelDistance, hotelDistanceMetric, hotelImages, hotelRating, hotelReviews, hotelStars, hotelCheckinTime, hotelCheckoutTime, hotelFacilities, hotelAmenities, hotelPolicies, rooms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HotelOfferDetailsSchema {\n");
    
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    supplierOfferId: ").append(toIndentedString(supplierOfferId)).append("\n");
    sb.append("    offerIndex: ").append(toIndentedString(offerIndex)).append("\n");
    sb.append("    offerTax: ").append(toIndentedString(offerTax)).append("\n");
    sb.append("    offerPrice: ").append(toIndentedString(offerPrice)).append("\n");
    sb.append("    offerCurrency: ").append(toIndentedString(offerCurrency)).append("\n");
    sb.append("    offerCancellationPolicies: ").append(toIndentedString(offerCancellationPolicies)).append("\n");
    sb.append("    checkinDate: ").append(toIndentedString(checkinDate)).append("\n");
    sb.append("    checkoutDate: ").append(toIndentedString(checkoutDate)).append("\n");
    sb.append("    hotelName: ").append(toIndentedString(hotelName)).append("\n");
    sb.append("    hotelDescription: ").append(toIndentedString(hotelDescription)).append("\n");
    sb.append("    hotelAddress: ").append(toIndentedString(hotelAddress)).append("\n");
    sb.append("    hotelLatitude: ").append(toIndentedString(hotelLatitude)).append("\n");
    sb.append("    hotelLongitude: ").append(toIndentedString(hotelLongitude)).append("\n");
    sb.append("    hotelDistance: ").append(toIndentedString(hotelDistance)).append("\n");
    sb.append("    hotelDistanceMetric: ").append(toIndentedString(hotelDistanceMetric)).append("\n");
    sb.append("    hotelImages: ").append(toIndentedString(hotelImages)).append("\n");
    sb.append("    hotelRating: ").append(toIndentedString(hotelRating)).append("\n");
    sb.append("    hotelReviews: ").append(toIndentedString(hotelReviews)).append("\n");
    sb.append("    hotelStars: ").append(toIndentedString(hotelStars)).append("\n");
    sb.append("    hotelCheckinTime: ").append(toIndentedString(hotelCheckinTime)).append("\n");
    sb.append("    hotelCheckoutTime: ").append(toIndentedString(hotelCheckoutTime)).append("\n");
    sb.append("    hotelFacilities: ").append(toIndentedString(hotelFacilities)).append("\n");
    sb.append("    hotelAmenities: ").append(toIndentedString(hotelAmenities)).append("\n");
    sb.append("    hotelPolicies: ").append(toIndentedString(hotelPolicies)).append("\n");
    sb.append("    rooms: ").append(toIndentedString(rooms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
