<?php
/**
 * SchemasApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Federated Content API
 *
 * Welcome to the Federated Content API following Open API Specification (Version 3.0.0)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SchemasApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SchemasApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for schemasGet
     *
     * Get schemas.
     *
     */
    public function testSchemasGet()
    {
    }

    /**
     * Test case for schemasGroupedByEndpointGet
     *
     * Get schemas grouped by endpoint.
     *
     */
    public function testSchemasGroupedByEndpointGet()
    {
    }

    /**
     * Test case for schemasIdDelete
     *
     * Delete schema.
     *
     */
    public function testSchemasIdDelete()
    {
    }

    /**
     * Test case for schemasIdGet
     *
     * Get schema.
     *
     */
    public function testSchemasIdGet()
    {
    }

    /**
     * Test case for schemasIdPatch
     *
     * Update schema.
     *
     */
    public function testSchemasIdPatch()
    {
    }

    /**
     * Test case for schemasPost
     *
     * Create schema.
     *
     */
    public function testSchemasPost()
    {
    }
}
