/* tslint:disable */
/* eslint-disable */
/**
 * Federated Content API
 * Welcome to the Federated Content API following Open API Specification (Version 3.0.0)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CarOfferRequestSchema
 */
export interface CarOfferRequestSchema {

    /**
     * Latitude for car pickup location.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    pickupLocationLatitude?: number;

    /**
     * Longitude for car pickup location.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    pickupLocationLongitude?: number;

    /**
     * Scheduled date for car pickup.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    pickupDate?: string;

    /**
     * Scheduled time for car pickup.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    pickupTime?: string;

    /**
     * Latitude for car dropoff location.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    dropoffLocationLatitude?: number;

    /**
     * Longitude for car dropoff location.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    dropoffLocationLongitude?: number;

    /**
     * Scheduled date for car dropoff.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    dropoffDate?: string;

    /**
     * Scheduled time for car dropoff.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    dropoffTime?: string;

    /**
     * Keyword to filter car offers.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    filterByKeyword?: string;

    /**
     * Minimum price to filter car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByPriceMin?: number;

    /**
     * Maximum price to filter car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByPriceMax?: number;

    /**
     * Minimum distance filter for car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByDistanceMin?: number;

    /**
     * Maximum distance filter for car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByDistanceMax?: number;

    /**
     * Minimum rating filter for car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByRatingMin?: number;

    /**
     * Maximum rating filter for car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByRatingMax?: number;

    /**
     * Minimum passengers capacity filter for car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByPassengersMin?: number;

    /**
     * Maximum passengers capacity filter for car offers.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    filterByPassengersMax?: number;

    /**
     * Types of cars to filter by.
     *
     * @type {Array<string>}
     * @memberof CarOfferRequestSchema
     */
    filterByType?: Array<string>;

    /**
     * Car rental companies to filter by.
     *
     * @type {Array<string>}
     * @memberof CarOfferRequestSchema
     */
    filterByCompany?: Array<string>;

    /**
     * Field to sort car offers by.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    sortBy?: string;

    /**
     * Order to sort car offers (asc, desc).
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    sortOrder?: string;

    /**
     * Page number for pagination.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    page?: number;

    /**
     * Number of offers per page.
     *
     * @type {number}
     * @memberof CarOfferRequestSchema
     */
    limit?: number;

    /**
     * Language for the offers.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    language?: string;

    /**
     * Currency for the offers.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    currency?: string;

    /**
     * Distance metric (mi/km) used in filters.
     *
     * @type {string}
     * @memberof CarOfferRequestSchema
     */
    metric?: string;
}
