/* tslint:disable */
/* eslint-disable */
/**
 * Federated Content API
 * Welcome to the Federated Content API following Open API Specification (Version 3.0.0)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FieldsBody
 */
export interface FieldsBody {

    /**
     * The unique identifier of the tenant
     *
     * @type {string}
     * @memberof FieldsBody
     */
    tenantId?: string;

    /**
     * The unique identifier of the schema
     *
     * @type {string}
     * @memberof FieldsBody
     */
    schemaId: string;

    /**
     * Name of the field
     *
     * @type {string}
     * @memberof FieldsBody
     */
    name: string;

    /**
     * Type of the field (e.g., string, number)
     *
     * @type {string}
     * @memberof FieldsBody
     */
    type: string;

    /**
     * Slug for the field
     *
     * @type {string}
     * @memberof FieldsBody
     */
    slug: string;

    /**
     * Description of the field
     *
     * @type {string}
     * @memberof FieldsBody
     */
    description?: string;

    /**
     * Status of the field, indicating if it is active
     *
     * @type {string}
     * @memberof FieldsBody
     */
    status?: FieldsBodyStatusEnum;

    /**
     * Flag indicating if the field can be used in search operations
     *
     * @type {boolean}
     * @memberof FieldsBody
     */
    isSearchable?: boolean;

    /**
     * Flag indicating if the field can be sorted
     *
     * @type {boolean}
     * @memberof FieldsBody
     */
    isSortable?: boolean;

    /**
     * Indicates if the field is a system field
     *
     * @type {boolean}
     * @memberof FieldsBody
     */
    system?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum FieldsBodyStatusEnum {
    Active = 'Active',
    Inactive = 'Inactive'
}

