/* tslint:disable */
/* eslint-disable */
/**
 * Federated Content API
 * Welcome to the Federated Content API following Open API Specification (Version 3.0.0)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FlightLegOfferRequestSchema } from './flight-leg-offer-request-schema';
import { FlightPassengerOfferRequestSchema } from './flight-passenger-offer-request-schema';
 /**
 * 
 *
 * @export
 * @interface FlightOfferResponseItemSchema
 */
export interface FlightOfferResponseItemSchema {

    /**
     * Unique identifier for the offer.
     *
     * @type {string}
     * @memberof FlightOfferResponseItemSchema
     */
    offerId?: string;

    /**
     * Unique identifier for the supplier’s offer.
     *
     * @type {string}
     * @memberof FlightOfferResponseItemSchema
     */
    supplierOfferId?: string;

    /**
     * Index of the offer for sorting purposes.
     *
     * @type {number}
     * @memberof FlightOfferResponseItemSchema
     */
    offerIndex?: number;

    /**
     * Price of the offer.
     *
     * @type {number}
     * @memberof FlightOfferResponseItemSchema
     */
    offerPrice?: number;

    /**
     * Currency of the offer price.
     *
     * @type {string}
     * @memberof FlightOfferResponseItemSchema
     */
    offerCurrency?: string;

    /**
     * Cancellation policies applicable to the offer.
     *
     * @type {{ [key: string]: any; }}
     * @memberof FlightOfferResponseItemSchema
     */
    offerCancelationPolicies?: { [key: string]: any; };

    /**
     * Name of the airline providing the offer.
     *
     * @type {string}
     * @memberof FlightOfferResponseItemSchema
     */
    offerAirlineName?: string;

    /**
     * Code of the airline providing the offer.
     *
     * @type {string}
     * @memberof FlightOfferResponseItemSchema
     */
    offerAirlineCode?: string;

    /**
     * Logo URL of the airline.
     *
     * @type {string}
     * @memberof FlightOfferResponseItemSchema
     */
    offerAirlineLogo?: string;

    /**
     * Array of flight legs, each described in FlightLegOfferRequestSchema.
     *
     * @type {Array<FlightLegOfferRequestSchema>}
     * @memberof FlightOfferResponseItemSchema
     */
    legs?: Array<FlightLegOfferRequestSchema>;

    /**
     * Array of passengers, each described in FlightPassengerOfferRequestSchema.
     *
     * @type {Array<FlightPassengerOfferRequestSchema>}
     * @memberof FlightOfferResponseItemSchema
     */
    passengers?: Array<FlightPassengerOfferRequestSchema>;

    /**
     * Array of codes for accessing special negotiated fares.
     *
     * @type {Array<string>}
     * @memberof FlightOfferResponseItemSchema
     */
    privateFareCodes?: Array<string>;
}
